#pragma once
#include <iostream>
#include <vector>
// GLM
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtx/transform.hpp>
#include <glm/gtc/type_ptr.hpp>
// GLEW
#define GLEW_STATIC
#include <GL/glew.h>
// GLFW
#include <GLFW/glfw3.h>
// Shaders
#include "Shader.h"
// SOIL
#include <SOIL/SOIL.h>
// Camera
#include "Camera.h"
#include "InputReader.h"